[package]
name = "libemulator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "2.0"
log = "0.4"
bitflags = "2.6"

num = "0.4"
number-bytes = "1.0"

libisa = { path = "../libisa" }
