[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "emulator"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/bin/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
strfmt = "0.2"

byteorder = "1.5"
bitflags = "2.6"
